# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
  stage: deploy
  script:
    - mkdir .public
    - pip install pandoc
    - pandoc README.md -o index.html
    - cp -r index.html .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
